@baseUrl = http://localhost:4000

###
GET {{baseUrl}}/userAll


###
GET {{baseUrl}}/projectAll


###
POST {{baseUrl}}/genJql
Content-Type: application/json

{
    "assignee" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "operater" : "OR",
    "reporter" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "project" : "SENSE-TEAM_IT",
    "beginDate": "2023-11-01",
    "endDate": "2023-12-31"
}

###
POST {{baseUrl}}/issueTotal
Content-Type: application/json

{
    "assignee" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "operater" : "OR",
    "reporter" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "project" : "SENSE-TEAM_IT",
    "beginDate": "2023-11-01",
    "endDate": "2023-12-31"
}


###
POST {{baseUrl}}/issueAll
Content-Type: application/json

{
    "assignee" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "operater" : "OR",
    "reporter" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "project" : "SENSE-TEAM_IT",
    "beginDate": "2023-11-01",
    "endDate": "2023-12-31",
    "pageNo": 0,
    "rowPerPage": 100
}
