@baseUrl = http://localhost:4000

###
GET {{baseUrl}}/userAll


###
GET {{baseUrl}}/projectAll


###
# GET {{baseUrl}}/issueAll


###
POST {{baseUrl}}/issueTotal
Content-Type: application/json

{
    "assignee" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "operater" : "AND",
    "reporter" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "project" : "SENSE-TEAM_IT",
    "beginDate": "2023-11-01",
    "endDate": "2023-12-31"
}


###   
POST {{baseUrl}}/issueAll
Content-Type: application/json

{
    "assignee" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "operater" : "AND",
    "reporter" : "712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba",
    "project" : "SENSE-TEAM_IT",
    "beginDate": "2023-11-01",
    "endDate": "2023-12-31"
}




#### Get Issue All
# POST {{baseUrl}}/search
# Authorization: {{credential}}
# Content-Type: application/json

# {
#    "fields": [
#     "status",
#     "created",
#     "updated",
#     "summary",
#     "assignee",
#     "reporter",
#     "project"
#   ],
#   "fieldsByKeys": false,
#   "jql": "assignee in (712020:e0c1f4d1-f728-4fa1-aec0-5d3b4ecff8ba) AND project = SENSE-TEAM_IT AND  updated >= 2023-11-01 AND updated <= 2023-12-31 order by updated DESC",
#   "startAt": 0,
#   "maxResults":100
# }
